$:
  vscode:
    - docker:
        build: ./Dockerfile
        volumes:
          - frontend/node_modules:cow
      env:
        CNB_WELCOME_CMD: |
          cd frontend && yarn dev
      runner:
        cpus: 32
      services:
        - vscode
        - docker
      stages:
        - name: start docker env
          script: echo "docker env"
        - name: 定时重启
          script:
            - sleep 5h && sh url.sh
            - sleep 5h && sh url.sh
            - sleep $(( (119*59) + (RANDOM % 59) )) && sh url.sh
          timeout: 12h